### ISSUE TITLE
Add links to awesome tools and tutorials for building chat bots | Hacktoberfest 2016

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/bots#12]
![bots3d](https://cloud.githubusercontent.com/assets/7190633/19622336/45dfa580-98c5-11e6-948a-dd7fa0253f65.png)

This repository contains links to awesome tools and resources for building chat bots. If you know of some cool tool or tutorial for making bots that is missing in this repo please make a Pull request. :tada: . Thanks for being awesome. Happy Hacktoberfest.

**Comment by janteuni** [comment]
Hello :)

I would like to add two links about bot analytics:
- Dialog - https://dialoganalytics.com/
- Dashbot - https://www.dashbot.io/

I was wondering if you wanted to create a new category like "Bot analytics", or if I add these two links in "Tools For Building Bots" ? and I will make a PR ;)

Cheers,

**Comment by hackerkid** [comment]
@janteuni I think Bot analytics deserve a category of it's own. Looking forward to your PR. :)
